name: Update JP Stocks

on:
  schedule:
    # 前場（9:00〜11:30 JST）
    - cron: "*/5 0-2 * * 1-5"

    # 後場（12:30〜15:00 JST）
    - cron: "*/5 3-6 * * 1-5"

  workflow_dispatch:



jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client yfinance pandas

      - name: Run script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python update.py
